### PR TITLE
deployment versions

### PR DESCRIPTION
**Pull request by mpetris**
the deploy folder contains the versions that should actually be integrated into the site

### CODE REVIEW

**Comment by olafgrabienski** [comment]
Thanks, can I already merge this PR?

**Comment by mpetris** [comment]
yes, this should work

**Comment by mpetris** [comment]
datamanagement.js and visualization-edge-bundling.vg.json need to be deployed to the fortext site
embed-module.html contains the code the four script imports and the code to be embedded into the front page (div+script)

**Comment by olafgrabienski** [comment]
So, `datamanagement.js` and `visualization-edge-bundling.vg.json` have to be integrated as files, and the rest should be part of the HTML template, right?

I'll give it a spin over the weekend.

**Comment by mpetris** [comment]
Yes, that's right. 

Just note that `datamanagement.js` is imported into the template via an import statement and `visualization-edge-bundling.vg.json` is loaded with the `fetch` function within the embedded code. But both have to be present as files.

**Comment by olafgrabienski** [comment]
Hm, it turned out that I didn't have much time over the weekend. I've however figured out how to change which Backdrop template file and some other things and will continue tomorrow.

**Pull request merged**
