### PR TITLE
support for video articles

### PR DESCRIPTION
**Pull request by mpetris**
support for embedded version
variable domain and url support
changed pie to custom arc marks to take advantage of the tree layout algorithm used for text marks

note: I changed the location of the data file to mimic a forTEXT API request

### CODE REVIEW

**Comment by olafgrabienski** [comment]
Merged!

> note: I changed the location of the data file to mimic a forTEXT API request

@mpetris Do you expect the visualization on https://olafgrabienski.github.io/vega-fortext/view-api.html to still work? If not, is there a way to test it?

**Comment by mpetris** [comment]
I changed the path in pull request #8 That should do the trick.

**Comment by olafgrabienski** [comment]
Ok, going to merge that!

**Comment by olafgrabienski** [comment]
Seems that it DID the trick, great!

**Pull request merged**
